### ISSUE TITLE
Most of the requests don't work 

### ISSUE THREAD

**Issue by artrayme** [ostis-ai/ts-sc-client#11]
**Describe the bug**
Hi. I tried to use this client to communicate with OSTIS but had a problem. Most of the requests are not working. Some of them don't pass the standard tests (from the test folder of this repository). Some queries break ostis at all (core dumped)

**To Reproduce**
1. Start OSTIS
2. Run tests (from attachments)
3. See the error in the console with OSTIS output

**Expected behavior**
Tests passed 🙂

**Screenshots**
Output for the "createElementsBySCs" test.
![image](https://user-images.githubusercontent.com/78550819/192119500-fe1e8a81-3516-4b66-888b-928a41267ac5.png)

But I have the same issue with "eventsCreate". 

**Additional context**
I used the NIKA system for the tests. It seems to work just like any other system (at least the tests of my JMantic client passed successfully). 

My tests:
[scClient.test.txt](https://github.com/ostis-ai/ts-sc-client/files/9639635/scClient.test.txt)

**Comment by artrayme** [comment]
And could you please tell me any project where this library is used? I didn't find any in ostis-ai...

**Comment by NikitaZotov** [comment]
Hi! Sorry that we didn't see this issue early. What ts-sc-client version do you use? I'll check it also in myself

**Comment by NikitaZotov** [comment]
Sc-web uses ts-sc-client in js-server to communicate with sc-server

**Comment by artrayme** [comment]
I've tested on 0.2.1 release and on version with latest changes from main branch (just clone this repo). But 0.2.1 doesn't have one important request - createElementsBySCs. Anyway, both versions dump the sc-machine on "setContent" test. 

``` 
  test("setContent", async () => {
    const content = "my_content";
    const linkContent = new ScLinkContent(content, ScLinkContentType.String);

    const res = await client.setLinkContents([linkContent]);

    expect(res).toHaveLength(1);
    expect(res[0]).toBeTruthy();

  });

```

And some screenshots:
1. Test output (you may notice that some of the tests run successfully, which means that the sc-machine is connected correctly). Similar output when running these tests on the client version from the main branch. 
![image](https://user-images.githubusercontent.com/78550819/192630869-e4f0a3bf-1552-4195-be8f-0841583e1203.png)

2. Sc-machine output 
![image](https://user-images.githubusercontent.com/78550819/192631452-3717458a-0171-4cef-b017-c658ccbd12ef.png)

It is also important to note that I am using the latest version of the NIKA system. And I have tried to reinstall it, but nothing has changed.
Text of the dump:
```
nika-problem-solver  | sc-server: /usr/include/nlohmann/json.hpp:3401: const value_type& nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::operator[](T*) const [with T = const char; ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::const_reference = const nlohmann::basic_json<>&; nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::value_type = nlohmann::basic_json<>]: Assertion `m_value.object->find(key) != m_value.object->end()' failed.
```

**Comment by artrayme** [comment]
> Sc-web uses ts-sc-client in js-server to communicate with sc-server

Hmm, this client is really specified as a dependency in the project, but I couldn't find any uses in the code (I checked the main branch). 
![image](https://user-images.githubusercontent.com/78550819/192635897-da95836c-fb91-4a3e-928a-da89c58d752b.png)

I found some use cases in the NIKA project UI, but it uses the previous major release. Does it have many differences in implementation and api? 
![image](https://user-images.githubusercontent.com/78550819/192636333-13ccbc71-883a-4abc-84d3-827ecac6aaec.png)

**Comment by NikitaZotov** [comment]
Most likely, you have the wrong version of the machine. The machine is frequently updated and strives for its release. Probably in Nick, that state of sc-machine is fixed in which, there is no method you need. We will update the docker image very soon. In the meantime, I think that it is possible to solve the problem on an individual basis.

**Comment by NikitaZotov** [comment]
Correct request and answer:
`[2022-09-30 23:56:18] [message_payload] [request] {"id":299,"type":"create_elements_by_scs","payload":["concept -> node;;"]}`
`[2022-09-30 23:56:18] [message_payload] [response] {"errors":[],"event":0,"id":299,"payload":[1],"status":1}`
